import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Creating a sidebar enables you to:
  // - create an ordered group of docs
  // - render a sidebar for each doc of that group
  // - provide next/previous navigation

  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  mainSidebar: [
    'intro', // Course overview
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System',
      link: {type: 'doc', id: 'robotic-nervous-system/index'},
      items: [
        'robotic-nervous-system/introduction-physical-ai',
        'robotic-nervous-system/ros2-architecture',
        'robotic-nervous-system/ros2-python-development',
        'robotic-nervous-system/urdf-robot-modeling',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin',
      link: {type: 'doc', id: 'digital-twin/index'},
      items: [
        'digital-twin/gazebo-fundamentals',
        'digital-twin/physics-simulation',
        'digital-twin/unity-integration',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI Robot Brain',
      link: {type: 'doc', id: 'ai-robot-brain/index'},
      items: [
        'ai-robot-brain/nvidia-isaac-sim',
        'ai-robot-brain/isaac-ros-perception',
        'ai-robot-brain/nav2-path-planning',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action',
      link: {type: 'doc', id: 'vision-language-action/index'},
      items: [
        'vision-language-action/voice-to-action',
        'vision-language-action/llm-cognitive-planning',
        'vision-language-action/capstone-autonomous-humanoid',
      ],
    },
    {
      type: 'category',
      label: 'Appendices',
      link: {type: 'doc', id: 'appendices/hardware-guide'}, // Link to the first appendix as overview
      items: [
        'appendices/hardware-guide',
        'appendices/troubleshooting',
        'appendices/cloud-setup',
        'appendices/resources',
      ],
    },
    'glossary',
    'instructor-guide', // Added instructor guide
    'student-resources/ros2_python_cheat_sheet', // Added student resources
    'student-resources/vla_reference_card', // Added student resources
    'video_embedding_instructions', // Added video embedding instructions
  ],
};

export default sidebars;
