<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="base_radius" value="0.15" />
  <xacro:property name="base_height" value="0.1" />
  <xacro:property name="wheel_radius" value="0.05" />
  <xacro:property name="wheel_width" value="0.02" />
  <xacro:property name="base_mass" value="5.0" />
  <xacro:property name="wheel_mass" value="0.1" />

  <!-- BASE LINK -->
  <link name="base_link">
    <visual>
      <geometry><cylinder radius="${base_radius}" length="${base_height}"/></geometry>
      <material name="blue">
        <color rgba="0 0 0.8 1"/>
      </material>
    </visual>
    <collision>
      <geometry><cylinder radius="${base_radius}" length="${base_height}"/></geometry>
    </collision>
    <inertial>
      <mass value="${base_mass}"/>
      <inertia ixx="${(base_mass/12)*(3*base_radius*base_radius + base_height*base_height)}"
               ixy="0.0" ixz="0.0"
               iyy="${(base_mass/12)*(3*base_radius*base_radius + base_height*base_height)}"
               iyz="0.0"
               izz="${(base_mass/2)*base_radius*base_radius}"/>
    </inertial>
  </link>

  <!-- WHEEL MACRO -->
  <xacro:macro name="wheel" params="prefix parent_link x_offset y_offset z_offset">
    <link name="${prefix}_wheel_link">
      <visual>
        <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
        <material name="black"><color rgba="0 0 0 1"/></material>
      </visual>
      <collision>
        <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
      </collision>
      <inertial>
        <mass value="${wheel_mass}"/>
        <inertia ixx="${(wheel_mass/12)*(3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
                 ixy="0.0" ixz="0.0"
                 iyy="${(wheel_mass/12)*(3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
                 iyz="0.0"
                 izz="${(wheel_mass/2)*wheel_radius*wheel_radius}"/>
      </inertial>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="${parent_link}"/>
      <child link="${prefix}_wheel_link"/>
      <origin xyz="${x_offset} ${y_offset} ${z_offset}" rpy="1.57075 0 0"/> <!-- Rotate wheel to be vertical -->
      <axis xyz="0 0 1"/>
    </joint>
  </xacro:macro>

  <!-- Add wheels -->
  <xacro:wheel prefix="left" parent_link="base_link" x_offset="0" y_offset="${base_radius + 0.01}" z_offset="0"/>
  <xacro:wheel prefix="right" parent_link="base_link" x_offset="0" y_offset="${-(base_radius + 0.01)}" z_offset="0"/>

  <!-- SENSOR LINK - simple range sensor -->
  <link name="range_sensor_link">
    <visual>
      <geometry><box size="0.02 0.02 0.02"/></geometry>
      <material name="red"><color rgba="1 0 0 1"/></material>
    </visual>
    <collision>
      <geometry><box size="0.02 0.02 0.02"/></geometry>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <inertia ixx="0.000001" ixy="0.0" ixz="0.0" iyy="0.000001" iyz="0.0" izz="0.000001"/>
    </inertial>
  </link>
  <joint name="range_sensor_joint" type="fixed">
    <parent link="base_link"/>
    <child link="range_sensor_link"/>
    <origin xyz="${base_radius} 0 ${base_height/2}" rpy="0 0 0"/> <!-- Front of base -->
  </joint>

</robot>
